apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOY_NAME
  namespace: NAMESPACE
spec:
  selector:
    matchLabels:
      app: DEPLOY_NAME
  replicas: REPLICAS
  template:
    metadata:
      labels:
        app: DEPLOY_NAME
    spec:
      containers:
        - image: IMAGE:TAG
          imagePullPolicy: IfNotPresent
          name: DEPLOY_NAME
          resources:
            limits:
              cpu: LIMIT_CPU
              memory: LIMIT_MEM
            requests:
              cpu: REQUEST_CPU
              memory: REQUEST_MEM
          command: COMMAND
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDeplaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          readnessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDeplaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
      imagePullSecrets:
        - name: registry-demo