apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: REPO_NAME-TAG
spec:
  serviceAccountName: tekton-build-sa
  pipelineRef:
    name: pipeline
  workspaces:
    - name: go-repo-pvc
      persistentVolumeClaim:
        claimName: go-repo-pvc
  params:
    - name: git_url
      value: GIT_URL
    - name: revision
      value: TAG
    - name: image
      value: IMAGE:TAG