name: "kubea"
mode: "dev"
port: 9000
ws_port: 8082
version: "v0.1.0"
start_time: "2023-12-12"
machine_id: 1
pod_log_tail_line: 2000
upload_path: ""

admin:
  username: "admin"
  password: "123456"

log:
  level: "debug"
  filename: "log/kubea.log"
  max_size: 200
  max_age: 30
  max_backups: 7

kube_configs:
  dev: "./config/dev-config"
  tst: "./config/test-config"

mysql:
  db_type: mysql
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "kubea_cicd"
  log_mode: false
  max_open_conns: 100  # 最大连接数
  max_idle_conns: 10  # 最大空闲连接
  max_life_time: 30 # 最大生存时间

redis:
  host: "127.0.0.1"
  port: 16379
  password: ""
  db: 0
  pool_size: 100

ci_cd:
  copy_job_name: "inf-lappcenter"
  jenkins_url: "https://test-jenkins.dayuan1997.com"
  user_password: "admin:11b51bea312eab12e147675012d26e1381530"
  cocos_jenkins_url: "http://173.30.99.254:8080"
  cocos_user_password: "admin:11b51bea312eab12e147675012d26e1381530"

gitlab:
  gitlab_url: "https://gitlab.dayuan1997.com"
  gitlab_token: "bJ-Nm6BZCxG6n-aF8aVt"